# Employee Selection Decision Support System

## Overview

This project is a comprehensive, web-based Decision Support System (DSS) designed to assist Human Resources departments in objectively evaluating and selecting the best employees. The system implements two prominent Multi-Criteria Decision Making (MCDM) algorithms: Simple Additive Weighting (SAW) and Multi-Objective Optimization on the basis of Ratio Analysis (MOORA). 

By automating the evaluation process, the system eliminates subjective biases, handles complex multi-criteria data efficiently, and provides transparent, mathematically verifiable results.

## Key Features

- Complete CRUD (Create, Read, Update, Delete) operations for managing Criteria, Alternatives (Employees), and Performance Assessments.
- Automated calculation engine implementing both SAW and MOORA algorithms.
- Transparent and explainable computation: the system returns step-by-step mathematical details, including normalization matrices, weighted scores, and optimization results.
- Comparative analysis module to evaluate and compare the ranking consistency between the SAW and MOORA methods.
- Data import capabilities via Excel and automated report generation in PDF format.
- Robust, high-performance RESTful API built with FastAPI.
- Modern, responsive, and user-friendly frontend interface.

## Technology Stack

### Backend
- **Language:** Python 3.12+
- **Framework:** FastAPI
- **Database:** PostgreSQL
- **ORM:** SQLAlchemy
- **Data Validation:** Pydantic

### Frontend
- **Framework:** React with TypeScript
- **Styling:** Tailwind CSS 4
- **Build Tool:** Vite

## Methodology

### Simple Additive Weighting (SAW)
SAW is a scoring method that calculates the weighted sum of the performance ratings of every alternative across all attributes. The system normalizes the decision matrix based on the attribute type (Benefit or Cost) and multiplies it by the criteria weight to determine the final preference value.

### Multi-Objective Optimization on the basis of Ratio Analysis (MOORA)
MOORA evaluates alternatives based on multiple criteria using ratio analysis. The system normalizes the decision matrix using the Euclidean distance method, applies criteria weights, and separates the calculation into Benefit and Cost objectives. The final appraisal score is calculated by subtracting the total cost score from the total benefit score.

## Prerequisites

Before setting up the project, ensure you have the following installed on your local machine:

- Python 3.12 or higher
- Node.js 18.x or higher (with npm or yarn)
- PostgreSQL 14.x or higher
- Git

## Installation and Setup

### 1. Clone the Repository

```bash
git clone https://github.com/your-username/spk-karyawan-saw-moora.git
cd spk-karyawan-saw-moora
```

### 2. Database Configuration

Create a new PostgreSQL database and user for the application.

```sql
CREATE DATABASE spk_karyawan;
CREATE USER spk_admin WITH ENCRYPTED PASSWORD 'your_secure_password';
GRANT ALL PRIVILEGES ON DATABASE spk_karyawan TO spk_admin;
```

### 3. Backend Setup

Navigate to the backend directory and set up the Python virtual environment.

```bash
cd backend
python -m venv venv

# Activate virtual environment
# On Windows:
venv\Scripts\activate
# On macOS/Linux:
source venv/bin/activate
```

Install the required Python dependencies:

```bash
pip install -r requirements.txt
```

### 4. Environment Variables

Create a `.env` file in the `backend` directory and configure your database connection string. Update the `database.py` file or use environment variables to load the following configuration:

```env
DATABASE_URL=postgresql://spk_admin:your_secure_password@localhost:5432/spk_karyawan
```

*Note: Ensure the database URL in `database.py` matches your local PostgreSQL credentials.*

Initialize the database tables (SQLAlchemy will create the tables automatically upon the first run, or you can run a dedicated migration script if configured).

### 5. Frontend Setup

Open a new terminal, navigate to the frontend directory, and install the dependencies.

```bash
cd frontend
npm install
```

## Running the Application

### Start the Backend Server

Ensure your virtual environment is activated and the database is running, then execute:

```bash
cd backend
uvicorn main:app --reload
```

The backend API will be available at `http://localhost:8000`.

### Start the Frontend Server

In a separate terminal window, execute:

```bash
cd frontend
npm run dev
```

The frontend application will be available at `http://localhost:5173` (or the port specified by Vite).

## API Documentation

The backend provides interactive API documentation automatically generated by FastAPI. Once the backend server is running, you can access the documentation at:

- **Swagger UI:** `http://localhost:8000/docs`
- **ReDoc:** `http://localhost:8000/redoc`

### Main API Endpoints

- `GET /api/kriteria` - Retrieve all criteria.
- `POST /api/kriteria` - Create a new criterion.
- `DELETE /api/kriteria/{id_kriteria}` - Delete a specific criterion.
- `GET /api/alternatif` - Retrieve all alternatives (employees).
- `POST /api/alternatif` - Create a new alternative.
- `DELETE /api/alternatif/{id_alternatif}` - Delete a specific alternative.
- `GET /api/penilaian` - Retrieve all performance assessments.
- `POST /api/penilaian` - Create a new assessment.
- `PUT /api/penilaian/{id_penilaian}` - Update an existing assessment.
- `DELETE /api/penilaian/{id_penilaian}` - Delete a specific assessment.
- `GET /api/calculate` - Execute the SAW and MOORA calculation engine and return the comprehensive results, including detailed mathematical steps and comparative analysis.

## Project Structure (Backend)

```text
backend/
│
├── main.py              # FastAPI application, routing, and middleware configuration
├── models.py            # SQLAlchemy ORM database models (Kriteria, Alternatif, Penilaian)
├── schemas.py           # Pydantic schemas for data validation and serialization
├── database.py          # Database engine configuration and session management
├── saw_moora.py         # Core business logic for SAW and MOORA algorithms
├── requirements.txt     # Python dependencies
└── .env                 # Environment variables (not included in version control)
```

## Security and Best Practices

- All API endpoints validate incoming data using Pydantic schemas to prevent malformed data injection.
- Database operations utilize SQLAlchemy ORM to prevent SQL injection vulnerabilities.
- Cascade delete rules are implemented at the ORM level to maintain referential integrity when criteria or alternatives are removed.
- The calculation engine includes strict validation to ensure mathematical operations (such as division) do not result in zero-division errors.

## License

This project is developed for academic and research purposes. Please refer to the LICENSE file for more details.
